name: Validate ARM Template Pipeline

pool:
  vmImage: 'windows-latest'

stages:
  - stage: ARMCI
    condition: always()
    jobs:
    - job: ARMTesting
      steps:
        - pwsh: mkdir "$(System.DefaultWorkingDirectory)\results"
          displayName: Create results folder

        - task: RunARMTTKTests@1
          displayName: Run ARM TTK tests 
          name: TTKtests
          inputs:
            templatelocation: '$(System.DefaultWorkingDirectory)\scripts'
            resultLocation: '$(System.DefaultWorkingDirectory)\results'
            skipTests: 'apiVersions Should Be Recent'

        - task: PublishTestResults@2
          displayName: Publish test restults
          name: PublishResults
          inputs:
            testResultsFormat: 'NUnit'
            testResultsFiles: '$(System.DefaultWorkingDirectory)\results\*-armttk.xml'
          condition: always()
  - stage: ValidateARM
    condition: always()
    jobs:
    - job: ARMValidation
      steps:
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Visual Studio Premium with MSDN(5f478995-39e1-49a0-9ef9-fb48dd84c58e)'
          subscriptionId: '5f478995-39e1-49a0-9ef9-fb48dd84c58e'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'AzSK-RG'
          location: 'Canada Central'
          templateLocation: 'Linked artifact'
          csmFile: '$(System.DefaultWorkingDirectory)/scripts/DeployAzureFunction.json'
          csmParametersFile: '$(System.DefaultWorkingDirectory)/scripts/azuredeploy.parameters.dev.json'
          deploymentMode: 'Validation'
      - task: AzSKARMTemplateChecker@4
        displayName: Validate ARM Template Security
        inputs:
          ARMTemplateFilePath: '$(System.DefaultWorkingDirectory)/scripts/DeployAzureFunction.json'
          ARMTemplateParameterFilePath: '$(System.DefaultWorkingDirectory)/scripts/azuredeploy.parameters.dev.json'